platform :ios, “9.0”
use_frameworks!
inhibit_all_warnings!

target 'TFBoccoSwift_Example' do
  pod 'TFBoccoSwift', :path => '../'
  
  pod 'Argo', '~> 3.1'
  pod 'Curry', '~> 2.3'
  pod 'Runes', '~> 3.2'
  pod 'AFNetworking', '~> 3.1'
  
  target 'TFBoccoSwift_Tests' do
  #inherit! :search_paths

#  pod 'Quick', '~> 0.8'
#  pod 'Nimble', '~> 3.0'
#  pod 'FBSnapshotTestCase'
#  pod 'Nimble-Snapshots'
  
  end
end
