use_frameworks!

target 'TFBoccoSwift_Example' do
  pod 'TFBoccoSwift', :path => '../'

  target 'TFBoccoSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
